# Generated by Django 6.0.1 on 2026-01-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('deadline', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('F', 'Finance'), ('P', 'Personal'), ('S', 'Study'), ('H', 'Finance'), ('W', 'Work'), ('O', 'Others')], max_length=1)),
            ],
        ),
    ]
